Added distance column to reachable_nodes
usc-isi-i2/kgtk pull request #581
Opened 2021-11-23 05:30 UTC by GrantXie

2021-11-23 19:38 UTC, GrantXie commented
The deleted part of the code is on the bottom part (starting line 573)

2021-11-23 19:41 UTC, CraigMiloRogers requested changes
Remove the community-detection code from this pull request, please.

2021-11-23 19:52 UTC, GrantXie commented
Just deleted the community-detection files and resolved conflicts

2021-11-30 19:00 UTC, CraigMiloRogers approved these changes

2021-11-30 19:00 UTC, merged